<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CocheSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('coches')->insert([
            ['id_coche' => 33, 'matricula' => '1234FML',    'marca' => 'Citroen',        'modelo' => 'C4',                  'id_cliente' => 27, 'imagen' => 'https://citroen-ausol.com/wp-content/uploads/2023/01/c4x-1.jpg',                                                                                                                                                                        'en_garaje' => false],
            ['id_coche' => 34, 'matricula' => '3183LMP',    'marca' => 'Citroen ',       'modelo' => 'C4 Puretech ',         'id_cliente' => 28, 'imagen' => 'https://citroen-ausol.com/wp-content/uploads/2023/01/c4x-1.jpg',                                                                                                                                                                        'en_garaje' => false],
            ['id_coche' => 35, 'matricula' => '1111DMG',    'marca' => 'volkswagen ',    'modelo' => 'Golf IV',              'id_cliente' => 29, 'imagen' => 'https://www.tuning.es/358576-large_default/anadido-rdx-vw-golf-4.jpg',                                                                                                                                                                  'en_garaje' => false],
            ['id_coche' => 36, 'matricula' => '0674GWK',    'marca' => 'Volkswagen ',    'modelo' => 'Golf 6',               'id_cliente' => 27, 'imagen' => 'https://www.automocionpere.com/storage/app/uploads/public/vehiculos/2358/volkswagen_golf_gti_gt_vr6_g60_rallye_rolling_stones_pink_floyd_manhattan_automocionpere_001.jpg', 'en_garaje' => false],
            ['id_coche' => 37, 'matricula' => '640765703',  'marca' => 'Volkswagen',     'modelo' => 'Golf 6',               'id_cliente' => 27, 'imagen' => 'https://www.automocionpere.com/storage/app/uploads/public/vehiculos/2358/volkswagen_golf_gti_gt_vr6_g60_rallye_rolling_stones_pink_floyd_manhattan_automocionpere_001.jpg', 'en_garaje' => false],
            ['id_coche' => 38, 'matricula' => 'b123',       'marca' => 'b',              'modelo' => 'b',                    'id_cliente' => 30, 'imagen' => 'b',                                                                                                                                                                                                                                    'en_garaje' => false],
            ['id_coche' => 39, 'matricula' => '0764GWK ',   'marca' => 'Volkswagen ',    'modelo' => 'Golf',                 'id_cliente' => 27, 'imagen' => 'https://citroen-ausol.com/wp-content/uploads/2023/01/c4x-1.jpg',                                                                                                                                                                        'en_garaje' => false],
            ['id_coche' => 40, 'matricula' => '0762GWK',    'marca' => 'Volskwagen',     'modelo' => 'Golf ',                'id_cliente' => 27, 'imagen' => '',                                                                                                                                                                                                                                     'en_garaje' => false],
            ['id_coche' => 41, 'matricula' => '1234AAA',    'marca' => 'Citroen',        'modelo' => 'XSara',                'id_cliente' => 33, 'imagen' => 'https://upload.wikimedia.org/wikipedia/commons/3/31/Citro%C3%ABn_Xsara_%28Facelift%29_%E2%80%93_Frontansicht%2C_17._M%C3%A4rz_2011%2C_W%C3%BClfrath.jpg',                                                                             'en_garaje' => false],
            ['id_coche' => 42, 'matricula' => '1637MVN',    'marca' => 'ja',             'modelo' => 'ja',                   'id_cliente' => 30, 'imagen' => 'https://citroen-ausol.com/wp-content/uploads/2023/01/c4x-1.jpg',                                                                                                                                                                        'en_garaje' => false],
            ['id_coche' => 43, 'matricula' => '1234ABC',    'marca' => 'Volkswagen',     'modelo' => 'Golf VI 1.6 TDI',      'id_cliente' => 27, 'imagen' => 'https://img.remediosdigitales.com/5915f2/vw-golf-bluemotion-prueba-1p/450_1000.jpg ',                                                                                                                                                   'en_garaje' => false],
            ['id_coche' => 44, 'matricula' => '5678DEF',    'marca' => 'BMW',            'modelo' => 'Serie 1',              'id_cliente' => 30, 'imagen' => 'https://www.autofacil.es/wp-content/uploads/2021/05/bmwdelantera.jpg',                                                                                                                                                                  'en_garaje' => false],
            ['id_coche' => 45, 'matricula' => '9012GHI',    'marca' => 'Mercedes-Benz',  'modelo' => 'Clase A',              'id_cliente' => 33, 'imagen' => 'https://www.km77.com/media/fotos/mercedes_clase_a_2018_5_puertas_6778_1.jpg',                                                                                                                                                           'en_garaje' => false],
            ['id_coche' => 48, 'matricula' => '9999AAA',    'marca' => 'Citroen',        'modelo' => 'XSara',                'id_cliente' => 34, 'imagen' => 'https://upload.wikimedia.org/wikipedia/commons/3/31/Citro%C3%ABn_Xsara_%28Facelift%29_%E2%80%93_Frontansicht%2C_17._M%C3%A4rz_2011%2C_W%C3%BClfrath.jpg',                                                                             'en_garaje' => false],
            ['id_coche' => 49, 'matricula' => '8888AAA',    'marca' => 'Citroen',        'modelo' => 'XSara',                'id_cliente' => 29, 'imagen' => 'https://upload.wikimedia.org/wikipedia/commons/3/31/Citro%C3%ABn_Xsara_%28Facelift%29_%E2%80%93_Frontansicht%2C_17._M%C3%A4rz_2011%2C_W%C3%BClfrath.jpg',                                                                             'en_garaje' => false],
            ['id_coche' => 50, 'matricula' => '7777AAA',    'marca' => 'Citroen',        'modelo' => 'XSara',                'id_cliente' => 29, 'imagen' => 'https://upload.wikimedia.org/wikipedia/commons/3/31/Citro%C3%ABn_Xsara_%28Facelift%29_%E2%80%93_Frontansicht%2C_17._M%C3%A4rz_2011%2C_W%C3%BClfrath.jpg',                                                                             'en_garaje' => false],
            ['id_coche' => 51, 'matricula' => '55555XXX',   'marca' => 'Citroen',        'modelo' => 'XSara',                'id_cliente' => 36, 'imagen' => 'https://upload.wikimedia.org/wikipedia/commons/3/31/Citro%C3%ABn_Xsara_%28Facelift%29_%E2%80%93_Frontansicht%2C_17._M%C3%A4rz_2011%2C_W%C3%BClfrath.jpg',                                                                             'en_garaje' => false],
            ['id_coche' => 52, 'matricula' => '5555XXX',    'marca' => 'Citroen',        'modelo' => 'XSara',                'id_cliente' => 36, 'imagen' => 'https://upload.wikimedia.org/wikipedia/commons/3/31/Citro%C3%ABn_Xsara_%28Facelift%29_%E2%80%93_Frontansicht%2C_17._M%C3%A4rz_2011%2C_W%C3%BClfrath.jpg',                                                                             'en_garaje' => false],
            ['id_coche' => 53, 'matricula' => '1111AAA',    'marca' => 'Volkswagen',     'modelo' => 'Golf',                 'id_cliente' => 29, 'imagen' => 'https://images.ctfassets.net/uaddx06iwzdz/4oYp6OpVnlIt5LFMBJufls/bad0e627bdcf2627eeff0928cc08e5e3/vw-golf-4-l-01.jpg',                                                                                                                'en_garaje' => true],
            ['id_coche' => 54, 'matricula' => 'aaa',        'marca' => 'aa',             'modelo' => 'aa',                   'id_cliente' => 37, 'imagen' => 'https://www.km77.com/media/fotos/mercedes_clase_a_2018_5_puertas_6778_1.jpg',                                                                                                                                                           'en_garaje' => true],
            ['id_coche' => 55, 'matricula' => '0000PPP',    'marca' => 'Citroen',        'modelo' => 'XSara',                'id_cliente' => 29, 'imagen' => 'a',                                                                                                                                                                                                                                    'en_garaje' => false],
            ['id_coche' => 56, 'matricula' => '8888PPP',    'marca' => 'Citroen',        'modelo' => 'XSara',                'id_cliente' => 29, 'imagen' => 'b',                                                                                                                                                                                                                                    'en_garaje' => false],
            ['id_coche' => 57, 'matricula' => 'prueba',     'marca' => 'prueba',         'modelo' => 'prueba',               'id_cliente' => 38, 'imagen' => 'b',                                                                                                                                                                                                                                    'en_garaje' => false],
            ['id_coche' => 58, 'matricula' => 'prueba2',    'marca' => 'prueba2',        'modelo' => 'prueba2',              'id_cliente' => 39, 'imagen' => 'b',                                                                                                                                                                                                                                    'en_garaje' => false],
            ['id_coche' => 59, 'matricula' => 'prueba3',    'marca' => 'prueba3',        'modelo' => 'prueba3',              'id_cliente' => 40, 'imagen' => 'https://images.ctfassets.net/uaddx06iwzdz/4oYp6OpVnlIt5LFMBJufls/bad0e627bdcf2627eeff0928cc08e5e3/vw-golf-4-l-01.jpg',                                                                                                                'en_garaje' => false],
        ]);
    }
}
