version: '3.8'

services:
  # Servidor Laravel (PHP + Node + Composer)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_server
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./proyecto:/var/www/html
    ports:
      - "5081:80"
      - "5173:5173"